# blender_manifest.toml

schema_version = "1.0.0"

id = "avatar_toolkit"
version = "0.5.2"
name = "Avatar Toolkit"
tagline = "A modern tool for importing and optimizing models for VRChat, Resonite, ChilloutVR, and other similar games."
maintainer = "989onan"
type = "add-on"

blender_version_min = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
network = "For the auto updater to work, you need to allow network access"
files = "Import/Export files, saving atlas images, saving preferences"
