# blender_manifest.toml

schema_version = "1.0.0"

id = "avatar_toolkit"
version = "0.0.1"
name = "Avatar Toolkit"
tagline = "A modern tool for importing and optimizing models for VRChat, Resonite, and other similar games."
maintainer = "Your Name <your.email@example.com>"
type = "add-on"

blender_version_min = "4.3.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
